### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by yuju-lee** [Doosane/Inventory-notification-system#26]
1. 비즈니스 로직의 흐름이 깨끗하게 분리되어 직관적이에요! 잘 작성하셨어요. 
2. 별도의 컴포넌트로 500개를 넘지 않게 tryAcquire()로 관리하신 부분도 잘 하셨어요. 
3. 상품과 재고를 별도 1:1 테이블로 관리함으로써, 도메인 분리를 시도한 아이디어가 좋아요! 
4. Rate Limiter 테스트까지 별도로 작성하신 것… 수고 너무 많으셨습니다.
5. 다만 구조 상 병렬로 알림을 전송할 때 Pessimistic Lock(@Lock(LockModeType.PESSIMISTIC_WRITE))이 반복적으로 걸릴 경우, 잠금 경합이 커질 수 있는데요! 현재 요구사항에서는 충분하니 알고만 넘어가셔도 좋을 것 같아요~ 
6. DTO 매핑 로직을 별도 전담 레이어나 매핑하여 분리하면 더 깔끔해 질 것 같아요! (이것도 과제 요구사항에는 큰 영향은 아닙니다!)
7. 안 쓰는 코드는 지워주세요! ㅎㅎ

과제 요구사항은 전부 만족하셨고, 코드 구조나 테스트도 너무 잘 작성해 주셨어요. README도 깔끔하게 잘 작성해 주셨습니다! 💯 
너무 수고 많으셨어요.

**Comment by BaekDoosan-maker** [comment]
헉 이렇게 늦은 시간에도 ㅜㅜ 피드백을 남겨 주셔서 감사합니다 ..!
말씀주신 내용을 참고해서, 다시 한번 생각해 보는 시간을 가지겠습니다

감사합니다..!

2024년 12월 22일 (일) 오전 3:09, Yuju Judy lee ***@***.***>님이 작성:

**Comment by yuju-lee** [comment]
프로젝트 이후에 한 번 다시 봐보세요! ㅎㅎ 더 좋은 아이디어가 또 생길 수도?! 지금도 내용은 너무 좋아요! 😄 👍  두산 님 프로젝트 주간도 파이팅이고 언제든지 질문 있으면 슬랙 주세요 ~

**Comment by BaekDoosan-maker** [comment]
다시 한번 말씀 주신 부분 확인해 보겠습니다..! 피드백 주셔서 감사합니다 :)
